### ISSUE TITLE
Clarify meaning of statuses

### ISSUE THREAD

**Issue by michquinn** [agile-learning-institute/mentorHub-mongodb#27]
https://github.com/agile-learning-institute/mentorHub-mongodb/blob/8142a5e0ff7439c578dbf66afce98a754bbee2a2/src/mongosh/institute-people-schema.json#L21-L23

**Comment by FlatBallFlyer** [comment]
Feel free to establish a standard for documenting enumerated values. You should be able to extend this to all of the enumerator based properties as part of refactoring the array's to a reusable component. The meanings of these are as follows:
pending - signed up and awaiting a mentor assignment
active - actively meeting with a mentor
drip - on a drip follow-up campaign, not active
archived - soft-delete indicator.

Validation logic about state change handled by the API. See the backlog in the README.md of that repository for details. Feel free to open an issue from those README.md backlog issues as that is where those really belong.

**Comment by FlatBallFlyer** [comment]
Merged this with issue #30
