### ISSUE TITLE
Consider using BSON Date type instead of String 

### ISSUE THREAD

**Issue by michquinn** [agile-learning-institute/mentorHub-mongodb#29]
https://github.com/agile-learning-institute/mentorHub-mongodb/blob/8142a5e0ff7439c578dbf66afce98a754bbee2a2/src/mongosh/institute-people-schema.json#L97-L99

See Mongo docs: https://www.mongodb.com/docs/manual/reference/bson-types/#date

**Comment by michquinn** [comment]
One place where this change would happen:

https://github.com/agile-learning-institute/mentorHub-person-api/blob/39d9a422754e290f2185e620642a5e51f6fa2b22/src/models/bread_crumb.go#L21

Relevant documentation from the `bson` package for handling transformations (points 9 and 1 in the two lists from the first link):
[1] https://pkg.go.dev/go.mongodb.org/mongo-driver/bson#hdr-Native_Go_Types
[2] https://pkg.go.dev/go.mongodb.org/mongo-driver@v1.13.1/bson/primitive#DateTime

**Comment by michquinn** [comment]
Using EJSON the format in the data files should be something like:
```json
"atTime": { "$date": "2010-05-23T12:21:05" }
```

**Comment by FlatBallFlyer** [comment]
Implemented in breadcrumb standardization
