### ISSUE TITLE
Topics schema has Partner status property

### ISSUE THREAD

**Issue by michquinn** [agile-learning-institute/mentorHub-mongodb#31]
https://github.com/agile-learning-institute/mentorHub-mongodb/blob/8142a5e0ff7439c578dbf66afce98a754bbee2a2/src/mongosh/institute-topics-schema.json#L32-L35

This appears to have been carried over by mistake and should be removed.

**Comment by avinashpathy** [comment]
Hi @michquinn,
Can I work on this one?

**Comment by FlatBallFlyer** [comment]
The status is still a valid attribute, but the values are simply Active and Archived - we must have a soft-delete indicator. Every collection should have a status property with at a minimum Active and Archived values.

**Comment by michquinn** [comment]
Good to know. If that's the case, did you want to leave it as an `enum` or would you prefer switching it to a boolean, perhaps something like `isActive`?

**Comment by FlatBallFlyer** [comment]
Keep it as an enum, there may be additional statuses in the future. Also, see my note on the PR about adding readme content

**Comment by michquinn** [comment]
You have notes to that effect in the README already [1], though it could be more explicit in regards to workflow when making changes. Shall I open another issue?

[1] https://github.com/agile-learning-institute/mentorHub-mongodb#build-and-test-the-container

**Comment by FlatBallFlyer** [comment]
I think you can use the existing PR to address more than one issue, or to make a minor refactor without an issue. I'd go ahead and knock out the readme updates along side the partner-status schema fix - at least the testing part. If you want to pick off some of the tasks in the existing issue that is a good way to move that change alone into a new issue for the existing PR. If you want to remove the Backlog part of the readme that is a good thing to catch as I"ve moved that content into issues. I would address the larger schema improvement refactor identified in [issue 30](https://github.com/agile-learning-institute/mentorHub-mongodb/issues/30) as a separate branch/PR
