### ISSUE TITLE
Finalize Partner schema

### ISSUE THREAD

**Issue by FlatBallFlyer** [agile-learning-institute/mentorHub-mongodb#36]
Review the existing partner schema and update as necessary

- [ ] Check Existing Schema 
- [ ] Implement Test Data with predictable _id values - this will include corresponding updates to people test data.

**Comment by modonnell0723** [comment]
How would you like the _id values to be structured?

**Comment by FlatBallFlyer** [comment]
We use the data files with the mongosh ``insertMany`` command. The data files currently do not provide a _id value, so id's are generated by mongo when they are inserted. If we specify a _id value, and use the ObjectId function we should be able to have predictable _id values that support cross-collection links... partner data file might look something like
```js
[
    {
       "_id": ObjectId("Codingcops.com"),
        "name": "Codingcops.com",
        "status": "Pending",
        "description": "Offshore coding company, Pakistan"
    }, ...
```
and a people-data file with
```js
[
    {
      "_id": ObjectId("James Smith"),
      "name": "James Smith",
      "status": "Pending",
      "partnerId": ObjectId("Codingcops.com"),
      "title": "Apprentice",
      ....
```
This would allow us to remove attributes like partnerName in favor of partnerId - see the schema files for details about id attributes. NOTE: The syntax above is not tested and probably has some errors
