### ISSUE TITLE
Create Curriculum Schema and Test Data

### ISSUE THREAD

**Issue by FlatBallFlyer** [agile-learning-institute/mentorHub-mongodb#39]
This is the primary UI for a Member. A Curriculum consists of a Roadmap (Now/Next/Later/Celebrated) of Resources that an apprentice is working on. Resources are added by the Mentor, and the apprentice can review the resources, reviews, and start or mark complete each item. There should also be a write-only resource review collection that is part of this domain.

**Comment by michquinn** [comment]
I hadn't seen this issue but had jotted down an initial idea [here](https://github.com/agile-learning-institute/mentorHub-mongodb/pull/47#issue-2116590895), will look into updating it based on your message above

**Comment by FlatBallFlyer** [comment]
From #46 - Michael Quinn

from the Pull Request for branch schema-topics-michquinn-issue35

thinking about how resources and topics may be used in Curriculum

```json
{
	"description": "A curriculum",
	"bsonType": "object",
	"required": ["name"],
	"properties": {
		"apprentice_id": {
			"description": "ID of the Apprentice this curriculum belongs to",
			"bsonType": "string"
		},
		"resumeGoals": {
			"description": "The list of Skills related to this topic",
			"bsonType": "array",
			"items": { "bsonType": "string" }
		},
		"resources": {
			"bsonType": "array",
			"items": {
				"bsonType": "object",
				"properties": {
					"name": { "bsonType": "string" },
					"started": { "bsonType": "Date" },
					"completed": { "bsonType": "Date" },
					"scope": { "bsonType": "string", "enum": [ "Celebrated", "Now", "Next", "Later" ] }
				}
			}
		}
	}
}
```
